package com.clouddocs.document;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import java.util.UUID;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class DocumentCatalogIntegrationTest {
    static final UUID TENANT_A=UUID.fromString("00000000-0000-0000-0000-000000000001"), TENANT_B=UUID.fromString("00000000-0000-0000-0000-000000000002");
    static final UUID ADMIN=UUID.fromString("10000000-0000-0000-0000-000000000001"), MEMBER=UUID.fromString("10000000-0000-0000-0000-000000000002"), VIEWER=UUID.fromString("10000000-0000-0000-0000-000000000003");
    @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
    @BeforeEach void seed(){jdbc.update("DELETE FROM document_tags");jdbc.update("UPDATE documents SET current_version_id=NULL");jdbc.update("DELETE FROM document_versions");jdbc.update("DELETE FROM documents");jdbc.update("DELETE FROM folders");jdbc.update("DELETE FROM tags");jdbc.update("DELETE FROM audit_events");jdbc.update("DELETE FROM memberships");jdbc.update("DELETE FROM tenants");jdbc.update("DELETE FROM users");
        user(ADMIN,"admin@example.com");user(MEMBER,"member@example.com");user(VIEWER,"viewer@example.com");user(UUID.fromString("10000000-0000-0000-0000-000000000004"),"other@example.com"); tenant(TENANT_A,"A");tenant(TENANT_B,"B"); membership(ADMIN,TENANT_A,"TENANT_ADMIN");membership(MEMBER,TENANT_A,"MEMBER");membership(VIEWER,TENANT_A,"VIEWER");membership(UUID.fromString("10000000-0000-0000-0000-000000000004"),TENANT_B,"TENANT_ADMIN");}
    @Test void documentCrudVersionArchiveAndPagination() throws Exception {String h="X-User-Email";String doc=mvc.perform(post("/api/v1/tenants/{t}/documents",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Report\",\"description\":\"draft\"}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();String id=doc.replaceAll(".*\"id\":\"([^\"]+)\".*","$1");mvc.perform(get("/api/v1/tenants/{t}/documents/{id}",TENANT_A,id).header(h,"viewer@example.com")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ACTIVE"));mvc.perform(patch("/api/v1/tenants/{t}/documents/{id}",TENANT_A,id).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Updated\",\"description\":\"changed\"}" )).andExpect(status().isOk());mvc.perform(post("/api/v1/tenants/{t}/documents/{id}/versions",TENANT_A,id).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"storageReference\":\"local/test-v1\",\"mediaType\":\"text/plain\",\"sizeBytes\":12}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.versionNumber").value(1));mvc.perform(post("/api/v1/tenants/{t}/documents/{id}/archive",TENANT_A,id).header(h,"member@example.com")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ARCHIVED"));mvc.perform(post("/api/v1/tenants/{t}/documents/{id}/versions",TENANT_A,id).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"storageReference\":\"local/test-v2\"}" )).andExpect(status().isBadRequest());mvc.perform(get("/api/v1/tenants/{t}/documents?page=0&size=1",TENANT_A).header(h,"viewer@example.com")).andExpect(status().isOk()).andExpect(jsonPath("$.size").value(1)).andExpect(jsonPath("$.totalElements").value(1));}
    @Test void rolesAndTenantIsolationAreEnforced() throws Exception {String h="X-User-Email";mvc.perform(post("/api/v1/tenants/{t}/documents",TENANT_A).header(h,"viewer@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Nope\"}")).andExpect(status().isForbidden());String id=mvc.perform(post("/api/v1/tenants/{t}/documents",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Private\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString().replaceAll(".*\"id\":\"([^\"]+)\".*","$1");mvc.perform(get("/api/v1/tenants/{t}/documents/{id}",TENANT_A,id).header(h,"other@example.com")).andExpect(status().isForbidden());}
    @Test void foldersTagsAndInvalidRelationships() throws Exception {String h="X-User-Email";String folder=mvc.perform(post("/api/v1/tenants/{t}/folders",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Root\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString().replaceAll(".*\"id\":\"([^\"]+)\".*","$1");mvc.perform(post("/api/v1/tenants/{t}/folders",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Bad\",\"parentId\":\"00000000-0000-0000-0000-000000000099\"}")).andExpect(status().isNotFound());String doc=mvc.perform(post("/api/v1/tenants/{t}/documents",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"Tagged\",\"folderId\":\""+folder+"\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString().replaceAll(".*\"id\":\"([^\"]+)\".*","$1");String tag=mvc.perform(post("/api/v1/tenants/{t}/tags",TENANT_A).header(h,"member@example.com").contentType(APPLICATION_JSON).content("{\"name\":\"legal\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString().replaceAll(".*\"id\":\"([^\"]+)\".*","$1");mvc.perform(post("/api/v1/tenants/{t}/documents/{d}/tags/{tag}",TENANT_A,doc,tag).header(h,"member@example.com")).andExpect(status().isNoContent());mvc.perform(get("/api/v1/tenants/{t}/documents/{d}/tags",TENANT_A,doc).header(h,"viewer@example.com")).andExpect(status().isOk()).andExpect(jsonPath("$[0].name").value("legal"));mvc.perform(delete("/api/v1/tenants/{t}/documents/{d}/tags/{tag}",TENANT_A,doc,tag).header(h,"member@example.com")).andExpect(status().isNoContent());}
    private void user(UUID id,String email){jdbc.update("INSERT INTO users(id,email,display_name,status) VALUES(?,?,?,'ACTIVE')",id,email,email);} private void tenant(UUID id,String name){jdbc.update("INSERT INTO tenants(id,name) VALUES(?,?)",id,name);} private void membership(UUID u,UUID t,String role){jdbc.update("INSERT INTO memberships(id,user_id,tenant_id,role) VALUES(?,?,?,?)",UUID.randomUUID(),u,t,role);}
}
