package com.clouddocs.document.application;
import com.clouddocs.audit.application.*; import com.clouddocs.audit.domain.AuditAction; import com.clouddocs.document.domain.*; import com.clouddocs.document.infrastructure.JdbcDocumentRepository; import com.clouddocs.identity.domain.User; import com.clouddocs.operations.api.InvalidRequestException; import com.clouddocs.tenancy.application.TenantAuthorizationService; import org.springframework.stereotype.Service; import java.util.*;
@Service public class DocumentService { private final JdbcDocumentRepository repo; private final FolderService folders; private final TenantAuthorizationService auth; private final AuditService audit; public DocumentService(JdbcDocumentRepository r,FolderService f,TenantAuthorizationService a,AuditService s){repo=r;folders=f;auth=a;audit=s;}
 public Document require(UUID tenant,UUID id){return repo.findByIdAndTenant(id,tenant);}
 public Document create(User u,UUID tenant,String name,String description,UUID folder){auth.requireWriteAccess(u,tenant);if(folder!=null)folders.require(tenant,folder);Document d=repo.insert(tenant,u.id(),folder,name.trim(),description);audit.record(tenant,u.id(),AuditAction.DOCUMENT_CREATED,"DOCUMENT",d.id());return d;}
 public Document get(User u,UUID tenant,UUID id){auth.requireMembership(u,tenant);return require(tenant,id);}
 public PageResponse<Document> list(User u,UUID tenant,DocumentStatus status,int page,int size){auth.requireMembership(u,tenant);if(page<0||size<1||size>100)throw new InvalidRequestException("page must be >= 0 and size must be between 1 and 100");return repo.findPage(tenant,status,page,size);}
 public Document update(User u,UUID tenant,UUID id,String name,String description,UUID folder){auth.requireWriteAccess(u,tenant);Document d=require(tenant,id);if(d.status()==DocumentStatus.ARCHIVED)throw new InvalidRequestException("Archived documents cannot be updated");if(folder!=null)folders.require(tenant,folder);repo.update(id,tenant,name.trim(),description,folder);Document updated=require(tenant,id);audit.record(tenant,u.id(),AuditAction.DOCUMENT_UPDATED,"DOCUMENT",id);return updated;}
 public Document archive(User u,UUID tenant,UUID id){auth.requireWriteAccess(u,tenant);Document d=require(tenant,id);if(d.status()!=DocumentStatus.ARCHIVED){repo.archive(id,tenant);audit.record(tenant,u.id(),AuditAction.DOCUMENT_ARCHIVED,"DOCUMENT",id);}return require(tenant,id);}
 public DocumentVersion version(User u,UUID tenant,UUID id,String ref,String media,String checksum,long size){auth.requireWriteAccess(u,tenant);Document d=require(tenant,id);if(d.status()==DocumentStatus.ARCHIVED)throw new InvalidRequestException("Archived documents cannot receive new versions");DocumentVersion v=repo.insertVersion(tenant,id,repo.nextVersion(id,tenant),ref,media,size,checksum,u.id());audit.record(tenant,u.id(),AuditAction.VERSION_CREATED,"DOCUMENT_VERSION",v.id());return v;}
}
